// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvwmddhlodfpqmxxwayw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2d21kZGhsb2RmcHFteHh3YXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjE0MzEsImV4cCI6MjA3NjE5NzQzMX0.wVJeOVvpE_djOX8VqJj2IUx_zsKYQ20E4rnj8zdpvW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});